Add more Commands
KZGlobalTeam/cs2kz-metamod pull request #122
Opened 2024-02-15 13:40 UTC by himenekocn

2024-02-16 21:50 UTC, GameChaos commented on src/kz/checkpoint/kz_checkpoint.cpp
>  }
instead of printing checkpoint index to chat, you could show it in the hud instead, probably in the timer panel.
something like `CP: 40/40 TPs: 30`. make sure to add 1 to current cp index, cos that's 0-indexed.

2024-02-16 22:31 UTC, zer0k-z requested changes

2024-02-17 02:57 UTC, himenekocn commented
Will make a change

2024-02-17 03:01 UTC, himenekocn commented on src/kz/checkpoint/kz_checkpoint.cpp
>  }
Can change panel display to PrintHTMLCentre? I think this is quite useful

2024-02-17 03:05 UTC, zer0k-z commented on src/kz/checkpoint/kz_checkpoint.cpp
>  }
`PrintHTMLCentre` is really distracting since it keeps flashing in the middle of the screen. It should be used for display events only in the future, (eg. distbug stats)

2024-02-17 03:07 UTC, himenekocn commented on src/kz/checkpoint/kz_checkpoint.cpp
>  }
> `PrintHTMLCentre` is really distracting since it keeps flashing in the middle of the screen. It should only be used to display events in the future, (eg. distbug stats)

Ok

2024-02-18 12:43 UTC, zer0k-z requested changes
For consistency, occurrences of `Jump Stats` and `JumpStats` should all be `Jumpstats` instead, treat it as a single word.

2024-02-18 12:43 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.h
> +	bool ShowJumpStats{}; // Need change to type
We're using `camelCase`, so it should be `showJumpStats` instead for style consistency.

2024-02-18 12:43 UTC, zer0k-z commented on src/kz/kz.h
> +	bool ShowPanel{};
We're using camelCase, so it should be `showPanel` instead for style consistency.

2024-02-18 12:43 UTC, zer0k-z commented on src/kz/kz.h
> +	bool IsShowPanel() { return this->ShowPanel; }
`IsShowPanel` should be `IsShowingPanel` instead

2024-02-18 12:43 UTC, zer0k-z commented on src/kz/kz_misc.cpp
> +	scmd::RegisterCmd("kz_stats",      Command_KzJumpStats, 	"Change Jump Stats print type.");
`kz_stats` is too vague, should name it to `kz_togglestats` instead. The command handler should be named `Command_KzToggleJumpStats` as well.

2024-02-18 12:43 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.h
> +	bool GetJumpStats() { return this->ShowJumpStats; } // Need change to type
`GetJumpStats` should be named `ShouldDisplayJumpStats` instead, to more accurately represent what it actually does.

2024-02-18 12:43 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	utils::CPrintChat(player->GetPawn(), "%s {grey}Jump Stats are now %s.", KZ_CHAT_PREFIX, this->ShowJumpStats ? "shown" : "hidden");
Function should be named `ToggleJumpstatsReporting` instead, to accurately reflect what it does. also the parameter doesn't do anything yet, so you should remove it until there's a need for it later.

The string could be formatted as "You have enabled jumpstats reporting." or "You have disabled jumpstats reporting.", which sounds much better.

2024-02-18 14:11 UTC, himenekocn commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	utils::CPrintChat(player->GetPawn(), "%s {grey}Jump Stats are now %s.", KZ_CHAT_PREFIX, this->ShowJumpStats ? "shown" : "hidden");
Get!

2024-02-18 14:53 UTC, himenekocn commented on src/kz/kz.h
> +	bool NoStats{};
> these variables don't respect the `camelCase` naming scheme, I think they should be renamed `showPanel` (because there will be more to hud than just the panel) and the stats variable should ideally be an integer, that way you can fine-tune the display level for the stats. See `JSOption` in the gokz repo for future options that should be added to cs2kz: https://github.com/KZGlobalTeam/gokz/blob/master/addons/sourcemod/scripting/include/gokz/jumpstats.inc

Will have a hud menu or chat menu? 

You are currently saying is to change it to !togglestats <displaylevel> ?

2024-02-18 15:16 UTC, zer0k-z requested changes

2024-02-18 15:16 UTC, zer0k-z commented on src/kz/checkpoint/kz_checkpoint.h
> +	i32 GetCheckPointsCount() { return this->checkpoints.Count(); }
This should be `GetCheckpointCount` instead, checkpoint is a single word.

2024-02-18 15:16 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.h
> +	bool ShouldDisplayJumpStats() { return this->showJumpStats; } // Need change to type
Should be `Jumpstats` instead of `JumpStats`

2024-02-18 15:19 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +				KZJumpstatsService::PrintJumpToChat(this->player, jump);
Should use Allman style brace placement here:
```c++
			if(this->ShouldDisplayJumpStats())
			{
				KZJumpstatsService::PrintJumpToChat(this->player, jump);
			}

```

2024-02-18 15:22 UTC, zer0k-z commented on src/kz/kz.h
> +	bool NoStats{};
No menu for the time being. It's fine to have no `displaylevel` for now, it's something to think of later down when we start rework on client preferences.

2024-02-18 15:56 UTC, zer0k-z requested changes

2024-02-18 15:56 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +void KZJumpstatsService::ToggleJumpstatsReporting(const char *StatsType)
Still need to get rid of `StatsType` here because it's unused.

2024-02-18 15:57 UTC, zer0k-z commented
Also there's a merge conflict that should be resolved as well.

2024-02-18 15:59 UTC, himenekocn commented
> Also there's a merge conflict that should be resolved as well.

I dont know why have merge conflict

2024-02-18 16:21 UTC, zer0k-z commented
The spacing for commands is different between dev and the PR, that's where the merge conflict happens

2024-02-18 16:53 UTC, himenekocn commented
> The spacing for commands is different between dev and the PR, that's where the merge conflict happens

I cant fix this merge conflict. I try.

2024-02-18 17:15 UTC, himenekocn commented
![QQ截图20240219011331](https://github.com/KZGlobalTeam/cs2kz-metamod/assets/9393126/b7935cc0-6904-463f-8316-8b4a53d9aacf)
@zer0k-z I tried

2024-02-18 17:20 UTC, himenekocn commented
Well done, Github. I don't have any Merge branch buttons on my sync fork

2024-02-18 17:20 UTC, zer0k-z commented
Should move the checkpoint to the centre panel (the one with timer) instead of the alert panel.

2024-02-18 17:21 UTC, himenekocn commented
> I pushed the merge commit, but you should move the checkpoint to the centre panel (the one with timer) instead of the alert panel. 3 lines alert panel is too small to be readable.

ok

2024-02-18 18:44 UTC, zer0k-z commented on src/kz/kz.h
> +	bool showPanel{};
this should be part of the HUD service.

2024-02-18 18:44 UTC, zer0k-z commented on src/kz/hud/kz_hud.cpp
> +		strcat(buffer, "\n");
should use `V_strncat` for consistency with the other `V_strncat` right under,

2024-02-18 18:45 UTC, zer0k-z commented on cfg/cs2kz.cfg
> +sv_cheats 0
This won't work if it's executed later into the map's lifecycle, (eg. something that fires after 5 seconds). For now, mappers should be responsible for enforcing sv_cheats to be 0.

2024-02-18 18:47 UTC, himenekocn commented on cfg/cs2kz.cfg
> +sv_cheats 0
> This won't work if it's executed later into the map's lifecycle, (eg. something that fires after 5 seconds). For now, mappers should be responsible for enforcing sv_cheats to be 0.

I tried, it work on some maps.

2024-02-18 18:50 UTC, himenekocn commented on cfg/cs2kz.cfg
> +sv_cheats 0
But it still needs to be forced to false, some player get ak47/flash/.. in my server.

2024-02-18 18:54 UTC, zer0k-z commented on cfg/cs2kz.cfg
> +sv_cheats 0
Yes, but it's just an effective fix for things executed before cs2kz.cfg. Entities like `point_servercommand` will break this 100%, and preferably we should make a rigid solution instead (like what's done in [gokz-global](https://github.com/KZGlobalTeam/gokz/blob/46f040199780505d40c3c8598abdb0a8b3d14d0f/addons/sourcemod/scripting/gokz-global.sp#L578))

2024-02-18 18:55 UTC, zer0k-z commented on cfg/cs2kz.cfg
> +sv_cheats 0
Also, this makes it very annoying for people who want to test the plugins because they would have to reset this cvar back to 1 again.

2024-02-18 19:54 UTC, himenekocn commented
@zer0k-z Should players reset checkpoints when they stop timing or are respawn?

2024-02-18 19:56 UTC, GameChaos commented
> @zer0k-z Should players reset checkpoints when they stop timing or are respawn?

no

2024-02-19 01:56 UTC, zer0k-z approved these changes

2024-02-19 02:46 UTC, merged