Dual mounting for KZ sound effects
KZGlobalTeam/cs2kz-metamod pull request #132
Opened 2024-03-02 19:52 UTC by himenekocn

2024-03-04 16:39 UTC, zer0k-z requested changes

2024-03-04 16:39 UTC, zer0k-z commented on src/kz/kz_misc.cpp
> +	scmd::RegisterCmd("kz_sound",		Command_KzToggleJsSound,	"Toggle JsSound play.");
Make this command more explicit (eg. `kz_jssound`), `kz_sound` could mean anything. Also the description could be "Toggle jumpstats sound effect."

2024-03-04 16:39 UTC, zer0k-z commented on src/kz/kz.h
> +#define KZ_SND_BEAT_RECORD "kz.wickedsick"
These aren't used anywhere, just remove it for now.

2024-03-04 16:39 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.h
> +	void ToggleJsSoundPlaying();
Could remove the `Playing` word from this function.

2024-03-04 16:39 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +        utils::CPrintChatAll("%s %s {grey}jumped %s%.1f {grey}units with a %s%s {grey}", KZ_CHAT_PREFIX, jump->GetJumpPlayer()->GetController()->m_iszPlayerName(), jumpColor, jump->GetDistance(), jum
Don't do this, this will needlessly spam player's chat. If you want to emit to everyone, make sure they can toggle the minimum broadcast tier as well, and this needs to make sure jsalways is disabled before sending messages to everyone.

2024-03-04 16:39 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +    const char *jumpColor = distanceTierColors[GetTiers];
Inconsistent indent?

2024-03-04 16:39 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +		return;
Inconsistent styling, use camelCase for variable and `if (xyz)` instead of `if(xyz)`. Also use allman braces for all conditions:

```
while (x == y)
{
    foo();
    bar();
}
```

2024-03-04 16:39 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +			if(this->ShouldPlayJumpstatSound())
Inconsistent styling, use `if (xyz)` instead of `if(xyz)`.

2024-03-04 16:39 UTC, zer0k-z commented on README.md
> +- Sounds addon Workshop ID [3171124941](https://steamcommunity.com/sharedfiles/filedetails/?id=3171124941) add to ```game/csgo/cfg/multiaddonmanager/multiaddonmanager.cfg```
MultiAddonManager just updated, use its interface to install and mount addons instead of requiring server owners to configure their own multiaddonmanager config file.

2024-03-04 16:39 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	utils::PlaySoundToClient(target->GetPlayerSlot(), distanceTierSounds[GetTier], 0.5f);
Need to make sure the addons are mounted and loaded before doing this.

2024-03-04 16:39 UTC, zer0k-z commented on src/utils/hooks.cpp
> +#include "kz/jumpstats/kz_jumpstats.h"
Why does this need to be included here?

2024-03-04 16:39 UTC, zer0k-z commented on src/kz/kz_misc.cpp
> +
Move this command registration to jumpstats.cpp instead.

2024-03-05 01:23 UTC, zer0k-z commented on src/kz/kz_misc.cpp
>  	scmd::RegisterCmd("kz_togglejs",	Command_KzToggleJumpstats,	"Change Jumpstats print type.");
Could also move these jumpstats to the service as well, now that js sound stuff goes to the service already.

2024-03-05 21:59 UTC, zer0k-z requested changes

2024-03-05 21:59 UTC, zer0k-z commented on src/cs2kz.cpp
> +	hooks::LoadAddons();
This doesn't really belongs to `hooks` namespace, should move it elsewhere, maybe to the main cs2kz.cpp or create a new file instead.

2024-03-05 21:59 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	DistanceTier GetTier = jump->GetJumpPlayer()->modeService->GetDistanceTier(jump->GetJumpType(), jump->GetDistance());
GetTier variable name doesn't respect `camelCase` variable naming convention, should use `tier` instead, simple and straight to the point

2024-03-05 21:59 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	DistanceTier GetTiers = jump->GetJumpPlayer()->modeService->GetDistanceTier(jump->GetJumpType(), jump->GetDistance());
Same over here as well, see the other comment about `GetTier`

2024-03-05 21:59 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	if (!GetTierChar || !V_stricmp("", GetTierChar))
This `GetTierChar` also doesn't respect variable name convention, rename it to `tierString/tierStr` instead. Also this doesn't compile, change it to a pointer type and use `strlen` for length check.

2024-03-05 21:59 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	int GetTierInt = V_StringToInt32(GetTierChar, -1);
This doesn't respect variable name convention either.

2024-03-05 21:59 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	DistanceTier GetTier = static_cast<DistanceTier>(GetTierInt);
This doesn't respect variable name convention either.

2024-03-05 21:59 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	DistanceTier GetTier = static_cast<DistanceTier>(GetTierInt);
Same variable name convention issue as above.

2024-03-05 21:59 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	player->jumpstatsService->SetPlaySoundMinDTier(GetTier);
Should move the equality check to the set function instead of doing it here so it's cleaner.

2024-03-05 21:59 UTC, zer0k-z commented on src/utils/hooks.cpp
> +IMultiAddonManager *g_IMultiAddonManager;
Name this `g_pMultiAddonManager` instead, since we're storing a pointer to this interface.

2024-03-05 21:59 UTC, zer0k-z commented on src/utils/hooks.cpp
> +	g_IMultiAddonManager->AddAddon(KZ_WORKSHOP_ADDONS_ID);
Does the server restart the map if the server didn't have this addons downloaded initially? If not you need to call `RefreshAddon` as well.

2024-03-06 04:22 UTC, himenekocn commented on src/utils/hooks.cpp
> +	g_IMultiAddonManager->AddAddon(KZ_WORKSHOP_ADDONS_ID);
oh, I forgot it, cause my server will auto change other map on startup.

2024-03-08 08:09 UTC, zer0k-z requested changes

2024-03-08 08:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	if (tier > target->jumpstatsService->GetBroadcastMinTier() && target->jumpstatsService->GetBroadcastMinTier() != DistanceTier_None)
Broadcasting implies the target is `everyone`, so there shouldn't be any `target` parameter. The broadcasting shouldn't care about whether the jumping player has jumpstats broadcast on or off either, the only thing it should care is that
- Whether jumpstats are enabled or not (I don't think this exists yet, there's only a display option for that)
- Whether player is having legitimate stats (normal style, no jsalways)

2024-03-08 08:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	}
Move this addon check logic inside `utils::PlaySoundToClient` instead and check for the `kz` prefix before the addon check.

2024-03-08 08:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	DistanceTier tier = static_cast<DistanceTier>(tierInt - 1);
"None" should be 0, that makes this logic much simpler.

2024-03-08 08:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	}
Inconsistent `if` block spacing.

2024-03-08 08:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	}
Inconsistent `if` block spacing.

2024-03-08 08:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +            			if(player->jumpstatsService->ShouldDisplayJumpstats() && tier > player->jumpstatsService->GetBroadcastMinTier() && player->jumpstatsService->GetBroadcastMinTier() != DistanceTier_None)
Inconsistent `if` block spacing.

2024-03-08 08:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	}
Inconsistent `if` block spacing.

2024-03-08 08:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +                			player->PrintChat(true, false, "%s {grey}jumped %s%.1f {grey}units with a %s%s", jump->GetJumpPlayer()->GetController()->m_iszPlayerName(), jumpColor, jump->GetDistance(), jumpColo
Should add the mode name at the end so people know that a 240 LJ is red because of them being on vanilla, for example. Copy it from the timer service.

2024-03-08 08:09 UTC, zer0k-z commented on src/utils/hooks.cpp
> +#include "kz/kz.h"
Does this include need to be here still?

2024-03-09 18:09 UTC, zer0k-z requested changes

2024-03-09 18:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.h
> +	int GetStringTierLevel(const char *tierString);
- `Tier` and `Level` mean effectively the same thing, rename this to `GetDistTierFromString` instead. 
- This shouldn't be a member function, should be a static function instead.
- This should return `DistanceTier` type.

2024-03-09 18:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.h
> +	DistanceTier GetPlaySoundMinDTier() { return this->soundMinTier; }
Rename this `GetPlaySoundMinDTier` to be consistent with the `GetBroadcastMinTier` above.

2024-03-09 18:09 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	for (int i = 0; i <= g_pKZUtils->GetGlobals()->maxClients; i++)
Use `i32` instead of `int` to be consistent with the rest of the code base.

2024-03-09 18:09 UTC, zer0k-z commented on README.md
> +For Play Kz sounds:
`For Play Kz sounds:` should be `(Optional) For KZ sound effects (eg. jumpstats):`

2024-03-10 11:18 UTC, zer0k-z requested changes

2024-03-10 11:18 UTC, zer0k-z commented on src/cs2kz.h
> +	bool IsAddonsMounted();
grammar, should be IsAddonMounted instead (no s in addon)

2024-03-10 14:51 UTC, zer0k-z approved these changes

2024-03-10 22:06 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +	if (target->jumpstatsService->GetSoundMinTier() > tier || target->jumpstatsService->GetSoundMinTier() > DistanceTier_Meh)
`target->jumpstatsService->GetSoundMinTier() > DistanceTier_Meh` should be `target->jumpstatsService->GetSoundMinTier() <= DistanceTier_Meh` instead.

2024-03-11 01:40 UTC, zer0k-z requested changes

2024-03-11 01:40 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +				player->PrintChat(true, false, "%s {grey}jumped %s%.1f {grey}units with a %s%s {grey}| %s", jump->GetJumpPlayer()->GetController()->m_iszPlayerName(), jumpColor, jump->GetDistance(), jumpColor, j
Don't use `jumpTypeShortStr` here, use the full `jumpTypeStr` instead. The mode name isn't colored (should be purple), and it should be `[Mode]` instead of `| Mode`

2024-03-11 01:40 UTC, zer0k-z commented on src/cs2kz.cpp
> +	g_pMultiAddonManager->RefreshAddons();
This call is too early on listen servers. Currently waiting for xen's response to see when would be the ideal time to call `RefreshAddons`, or this should be something handled in his plugin instead.

2024-03-11 10:02 UTC, zer0k-z requested changes

2024-03-11 14:01 UTC, zer0k-z requested changes

2024-03-11 16:50 UTC, zer0k-z approved these changes

2024-03-11 23:51 UTC, zer0k-z requested changes

2024-03-11 23:51 UTC, zer0k-z commented on src/kz/jumpstats/kz_jumpstats.cpp
> +				player->PrintChat(true, false, "%s {grey}jumped %s%.1f {grey}units with a %s%s {grey}[%s]", jump->GetJumpPlayer()->GetController()->m_iszPlayerName(), jumpColor, jump->GetDistance(), jumpColor, j
This is still using `jumpTypeShortStr` and not `jumpTypeStr` so the comment shouldn't have been resolved here.
Don't color just the jump type the same color as the distance, use another color instead, and add purple to the mode name at the end (that should be in purple: `{grey}[{purple}%s{grey}]`).

2024-03-16 19:04 UTC, zer0k-z approved these changes

2024-03-16 19:34 UTC, merged