Add kz_goto command
KZGlobalTeam/cs2kz-metamod pull request #196
Opened 2024-07-07 14:05 UTC by jonassjoh

Hello!

Thought I'd try to start helping out with the development, and felt like the kz_goto command would be a good starting point for me to get more of a feel for it all.

I have quite a few questions, but I'm also going away on holiday for a little while. So I thought I'd make the PR and ask them in here (see comments). Perhaps the code is good enough as it is in it's current state.

I tried my best to mimic already existing code. But there must be better ways to do some of the things I've done.

Feel free to roast the code, or me. I'm here in part to learn, and I've not written any C++ in... 5 years? Has it been that long...
Also, since I'm going away for a little while, also feel free to hijack things if you feel the need.

2024-07-07 14:06 UTC, jonassjoh commented on src/kz/goto/kz_goto.cpp
> +	if (!this->player->timerService->GetValidTimer())
Is this the correct way to check if the timer is running? I failed to get a kz map to even load (lol), so I could not really test any of those parts.

2024-07-07 14:06 UTC, jonassjoh commented on src/kz/goto/kz_goto.cpp
> +		this->player->languageService->PrintChat(true, false, "Stop your timer before trying to teleport.");
Recurring problem, I'm not really sure how to allow for translations.

2024-07-07 14:07 UTC, jonassjoh commented on src/kz/goto/kz_goto.cpp
> +		if (!controller)
This check felt weird, but I could not figure out a better way.

2024-07-07 14:08 UTC, jonassjoh commented on src/kz/goto/kz_goto.cpp
> +			if (this->player->GetController()->GetTeam() == CS_TEAM_SPECTATOR)
Are there any potential problems with trying to force the player out of spec like this?
Maybe the timer should also be started?

2024-07-07 14:08 UTC, jonassjoh commented on src/kz/goto/kz_goto.cpp
> +			this->player->timerService->TimerStop();
Maybe an unnessesary line due to the first if-statement in the function?

2024-07-07 14:11 UTC, jonassjoh commented on src/kz/goto/kz_goto.cpp
> +				ms->m_vecLadderNormal(vec3_origin);
This just felt weird to me. But my question is rather... is there any good documentation for all of this? I felt like my google-skills were failing me, because I failed to research almost any of my questions.

Like: What are the different things even? Like what is a pawn? How does it differ from the other uhh..."pawns"?

Or perhaps there isn't really any documentation? The valve dev pages seems to have a lot of empty and "TODO" sections.

2024-07-07 14:15 UTC, jonassjoh commented
And a more general (perhaps I should be asking all of this elsewhere), but is there a guide as to how to better be in dev mode? My process was to:

1. Shut down dedicated server.
2. Run `ambuild`.
3. Copy over the `cs2kz` folder to the dedicated server.
4. Restart the dedicated server.

It felt... tedious to say the least. But I didn't even really know where to start to get a more smooth development experience. Hot reload would be the dream.

2024-07-07 14:18 UTC, jonassjoh commented on src/kz/goto/kz_goto.cpp
> +	for (i32 i = 0; i <= g_pKZUtils->GetGlobals()->maxClients; i++)
Is there a better way to get a specific player? Feels like there should be a global function or something for it. Either by fuzzy name search, exact name, or index/id.

2024-07-07 14:40 UTC, AlphaKeks reviewed
Hey! Thank you for contributing, I'll leave my 2 cents here.

I'm new to the code base as well, so take everything I say with a grain of salt :)

2024-07-07 14:40 UTC, AlphaKeks commented on src/kz/goto/kz_goto.cpp
> +	if (!this->player->timerService->GetValidTimer())
If [the `!stop` code](https://github.com/jonassjoh/cs2kz-metamod/blob/143da55dc4b3286108715f049bce6fb7080f953a/src/kz/timer/kz_timer.cpp#L631-L634) is to be believed, it should be.

The plugin should load kz_checkmate automatically if you use the default configuration, did it crash or something? I made a docker template for easily running a server locally a while back, and zer0k forked it: https://github.com/zer0k-z/cs2kz-server

Maybe it'll be easier to run in a standardized environment?

2024-07-07 14:40 UTC, AlphaKeks commented on src/kz/goto/kz_goto.cpp
> +		this->player->languageService->PrintChat(true, false, "Stop your timer before trying to teleport.");
You either add a phrase to one of the existing files in `translations/`, or make your own file, e.g. `cs2kz-goto.phrases.txt`. You would then add an entry like this:
```
"Phrases"
{
	"Teleport Warning"
	{
		"en"		"{red}Stop your timer before trying to teleport."
	}
}
```
And then reference it in your code by its name:
```cpp
this->player->languageService->PrintChat(true, false, "Teleport Warning");
```

Some of the translations can also take formatting arguments; you specify them with a `#format` clause in the translation file and pass them in as parameters when calling `PrintChat()` etc.

See the existing translations for examples.

2024-07-07 14:40 UTC, AlphaKeks commented on src/kz/goto/kz_goto.cpp
> +	for (i32 i = 0; i <= g_pKZUtils->GetGlobals()->maxClients; i++)
[`PlayerManager::ToPlayer()`](https://github.com/jonassjoh/cs2kz-metamod/blob/143da55dc4b3286108715f049bce6fb7080f953a/src/player/player.h#L141-L146) has a bunch of overloads that could be useful. It also just exposes [the global player list as a public member](https://github.com/jonassjoh/cs2kz-metamod/blob/143da55dc4b3286108715f049bce6fb7080f953a/src/player/player.h#L158), so you can just index directly if you feel adventurous :)

I agree though that there should be an overload that does fuzzy name matching. Maybe something you could implement in a different PR? :)

2024-07-07 14:40 UTC, AlphaKeks commented on src/kz/goto/kz_goto.cpp
> +				ms->m_vecLadderNormal(vec3_origin);
I believe these are just Valve terms, they haven't changed in 20 years though, so whatever a "pawn" is, old sourcemod documentation should probably cover it.

That being said, I found the documentation to be quite bad as well, and cs2kz itself doesn't have any either. I hope this will change before release.

You can also just ask though; AlliedModders has a Discord server, and you can ask questions in the cs2kz section on the KZ discord as well (in the forum preferably).

2024-07-07 14:43 UTC, AlphaKeks commented
> And a more general (perhaps I should be asking all of this elsewhere), but is there a guide as to how to better be in dev mode? My process was to:
> 
>     1. Shut down dedicated server.
> 
>     2. Run `ambuild`.
> 
>     3. Copy over the `cs2kz` folder to the dedicated server.
> 
>     4. Restart the dedicated server.
> 
> 
> It felt... tedious to say the least. But I didn't even really know where to start to get a more smooth development experience. Hot reload would be the dream.

See [this comment](https://github.com/KZGlobalTeam/cs2kz-metamod/pull/196#discussion_r1667705760) that I was writing before you posted this :)

My personal workflow is to have a tmux pane with a shell inside the container, and then just run `make plugin && make runkz` everytime I make a change, works pretty smoothly!

2024-07-07 15:00 UTC, zer0k-z requested changes

2024-07-07 15:00 UTC, zer0k-z commented on translations/cs2kz-commands.phrases.txt
> +		"ua"		""
If you don't have a translation for a particular language, don't put an empty string/put the key value in at all, that way it will properly fall back to the default language (english)

2024-07-07 15:00 UTC, zer0k-z commented on src/kz/goto/kz_goto.cpp
> +		this->player->languageService->PrintChat(true, false, "Stop your timer before trying to teleport.");
You can make a cs2kz-goto.phrases.txt file, add your preferred translation key (say in this case `Goto - Error Message (Timer Running)`).
The file would be automatically loaded by the plugin, and the content would look something like this:
```
"Phrases"
{
	"Goto - Error Message (Timer Running)"
	{
		"en"		"{darkred}Stop your timer before trying to teleport."
	}
}
```

2024-07-07 15:00 UTC, zer0k-z commented on src/kz/goto/kz_goto.cpp
> +	if (!this->player->timerService->GetValidTimer())
No, this should be `GetTimerRunning()`. `GetValidTimer` doesn't have an use right now (because right now all runs have a valid timer or doesn't have one running at all)

2024-07-07 15:00 UTC, zer0k-z commented on src/kz/goto/kz_goto.cpp
> +	for (i32 i = 0; i <= g_pKZUtils->GetGlobals()->maxClients; i++)
There's already a way to get the player through index/id through `CKZPlayerManager::ToPlayer`, but it would be nice for the class implement a way to obtain a player through names, though you would have to take into account cases where there are multiple matches.

2024-07-07 15:00 UTC, zer0k-z commented on src/kz/goto/kz_goto.cpp
> +			if (this->player->GetController()->GetTeam() == CS_TEAM_SPECTATOR)
When teleporting to another timer, the timer shouldn't be running. When in spectator, the timer is paused or not running, since the player can't goto with a timer on that shouldn't be a problem.

2024-07-07 15:00 UTC, zer0k-z commented on src/kz/goto/kz_goto.cpp
> +				ms->m_vecLadderNormal(vec3_origin);
The controller/pawn scheme first appeared in 2020 inside dota 2 code, so it makes sense that there isn't any documentation around it.

The player class in CSGO is basically split into the controller and the pawn in CS2 (so basically you and the "characters" under your control). There are only one controller but it could be controlling multiple pawns (in CS2, you have a player pawn and an observer pawn). Most (if not all) of the movement information is stored inside the player character, which is the player pawn in this case.

Inside each pawn contain "services" which are class instances containing functions and informations related to a specific functionality. In KZ it's usually the movement services class that is the most interesting.

2024-07-07 15:00 UTC, zer0k-z commented on src/kz/goto/kz_goto.cpp
> +			this->player->timerService->TimerStop();
You could make it so it stops the timer if you teleport to someone else (which is csgo's behavior)

2024-07-07 15:06 UTC, zer0k-z commented
> And a more general (perhaps I should be asking all of this elsewhere), but is there a guide as to how to better be in dev mode? My process was to:
> 
> 1. Shut down dedicated server.
> 2. Run `ambuild`.
> 3. Copy over the `cs2kz` folder to the dedicated server.
> 4. Restart the dedicated server.
> 
> It felt... tedious to say the least. But I didn't even really know where to start to get a more smooth development experience. Hot reload would be the dream.

You can skip step 3 by creating a symlink from `build/package/addons/cs2kz` to `<whereever the dedicated server is>/addons/cs2kz`. Hot reload is only possible if there is another dummy plugin running that you can easily load/unload (then you can unload cs2kz, reload the dummy plugin, run `ambuild`, reload the plugin, but that's a metamod related bug/"feature". Also I'm not sure if hot reload support is fully functional yet, so your best bet is probably to just do the symlink and skip 25% of the steps.

2024-07-24 20:03 UTC, jonassjoh commented on src/kz/goto/kz_goto.cpp
> +	if (!this->player->timerService->GetValidTimer())
> No, this should be `GetTimerRunning()`. `GetValidTimer` doesn't have an use right now (because right now all runs have a valid timer or doesn't have one running at all)

The name made me think that it was not `true` while paused 😬

2024-07-24 21:19 UTC, jonassjoh commented
I think I corrected everything that was mentioned, but I am a bit tired so it's not impossible that I forgot something.

The docker method seems to work rather nice! Was a bit of a hassle getting it to work, but it's nicer than what I was doing before.

2024-07-24 21:20 UTC, jonassjoh commented on src/kz/goto/kz_goto.cpp
> +	if (!this->player->timerService->GetValidTimer())
> If [the `!stop` code](https://github.com/jonassjoh/cs2kz-metamod/blob/143da55dc4b3286108715f049bce6fb7080f953a/src/kz/timer/kz_timer.cpp#L631-L634) is to be believed, it should be.
> 
> The plugin should load kz_checkmate automatically if you use the default configuration, did it crash or something? I made a docker template for easily running a server locally a while back, and zer0k forked it: https://github.com/zer0k-z/cs2kz-server
> 
> Maybe it'll be easier to run in a standardized environment?

docker <3

2024-07-24 21:25 UTC, jonassjoh commented on src/kz/goto/kz_goto.cpp
> +	if (!this->player->timerService->GetValidTimer())
> If [the `!stop` code](https://github.com/jonassjoh/cs2kz-metamod/blob/143da55dc4b3286108715f049bce6fb7080f953a/src/kz/timer/kz_timer.cpp#L631-L634) is to be believed, it should be.
> 
> The plugin should load kz_checkmate automatically if you use the default configuration, did it crash or something? I made a docker template for easily running a server locally a while back, and zer0k forked it: https://github.com/zer0k-z/cs2kz-server
> 
> Maybe it'll be easier to run in a standardized environment?

Uhh... is it possible to add a bot through the console? bot_add does nothing for me in the docker server.

And a bonus question: if I try to run the command from the client I get "Client Jnas Cage(0) tried to execute command "bot_add_t" but it is not marked FCVAR_CLIENT_CAN_EXECUTE.", do either of you happen to know how to fix this? Would be useful to be able to move bots around etc by eg. bot_place, but can't do that from the server console.

2024-07-24 21:38 UTC, zer0k-z commented on src/kz/goto/kz_goto.cpp
> +	if (!this->player->timerService->GetValidTimer())
bot_add doesn't work on a map without nav meshes (eg. kz maps), try it on an official Valve map instead

2024-07-24 21:40 UTC, zer0k-z commented on src/kz/goto/kz_goto.cpp
> +	if (!this->player->timerService->GetValidTimer())
You can also run kz on a listen server so you can do commands like bot_place (see [this](https://docs.femboy.kz/wiki/cs2/guides/listen))

2024-07-29 16:19 UTC, zer0k-z commented
There are now merge conflicts, could you rebase the PR to the latest dev's commit?

2024-07-30 19:07 UTC, jonassjoh commented
> There are now merge conflicts, could you rebase the PR to the latest dev's commit?

Idk if there were other changes that had to be made as well. I'm going away for a few days again, so didn't really have much more time than to do a simple merge and fix the conflicts.

2024-08-03 03:34 UTC, merged